### ISSUE TITLE
Move generation

### ISSUE THREAD

**Issue by brianprichardson** [markus7800/Beth#1]
Thank you for sharing your work.

From the position
r2qkb1r/1Q3pp1/pN1p3p/3P1P2/3pP3/4n3/PP4PP/1R3RK1 w - -
using the "standard" perft function, I get a different count from my engine Tinker and Crafty

Perhaps the number of positions you cite is not the same as the typical "perft"?

Tinker:
`perft 6
depth 1  netcount               37      makecount               37
depth 2  netcount              944      makecount              981
depth 3  netcount            34730      makecount            35711
depth 4  netcount           868457      makecount           904168
depth 5  netcount         31825308      makecount         32729476
depth 6  netcount        804483605      makecount        837213081
44.80 seconds
19.0M per second

Crafty v25.6

machine has 24 processors

White(1): r2qkb1r/1Q3pp1/pN1p3p/3P1P2/3pP3/4n3/PP4PP/1R3RK1 w - -
White(1): d

       +---+---+---+---+---+---+---+---+
    8  |<R>| . |   |<Q>|<K>|<B>|   |<R>|
       +---+---+---+---+---+---+---+---+
    7  | . |-Q-| . |   | . |<P>|<P>|   |
       +---+---+---+---+---+---+---+---+
    6  |<P>|-N-|   |<P>|   | . |   |<P>|
       +---+---+---+---+---+---+---+---+
    5  | . |   | . |-P-| . |-P-| . |   |
       +---+---+---+---+---+---+---+---+
    4  |   | . |   |<P>|-P-| . |   | . |
       +---+---+---+---+---+---+---+---+
    3  | . |   | . |   |<N>|   | . |   |
       +---+---+---+---+---+---+---+---+
    2  |-P-|-P-|   | . |   | . |-P-|-P-|
       +---+---+---+---+---+---+---+---+
    1  | . |-R-| . |   | . |-R-|-K-|   |
       +---+---+---+---+---+---+---+---+
         a   b   c   d   e   f   g   h

White(1): perft 6
total moves=804483605  time=19.88
White(1):`

**Comment by markus7800** [comment]
Thanks for pointing this out!
Indeed for the number given in the readme I also counted inner tree nodes while normal perft only counts leaf nodes (but there was also a bug in that :) ).
Running normal perft resulted in the number you stated.
